name: Bug Report
description: Found a bug or encountered a crash? Please report it here.
labels: [ bug ]
body:
    -   type: markdown
        attributes:
            value: |
                Please follow following guidelines before reporting an issue:
                1) Ensure that you are running on the latest Refined Storage 2 version.
                2) Ensure that your issue hasn't already been posted.
                3) Be as detailed as possible.
                4) Try to reproduce the issue with only Refined Storage 2 installed, if possible.

                Respecting these guidelines will help us solve issues faster.

                We might close your issue, without explanation, if you do not follow these guidelines.
    -   type: textarea
        id: description
        attributes:
            label: Describe the bug
            description: |
                Ensure that you are using the most recent version.
                If applicable, also tell us what you expected to happen instead.
        validations:
            required: true
    -   type: textarea
        id: reproduce
        attributes:
            label: How can we reproduce this bug or crash?
            placeholder: |
                1.
                2.
                3.
        validations:
            required: true
    -   type: dropdown
        id: minecraft
        attributes:
            label: What Minecraft version is this bug happening on?
            options:
                - Minecraft 1.17.1
    -   type: input
        id: fabric
        attributes:
            label: What Fabric version is this happening on?
        validations:
            required: true
    -   type: input
        id: rs
        attributes:
            label: What Refined Storage version is this happening on?
        validations:
            required: true
    -   type: textarea
        id: logs
        attributes:
            label: Relevant log output
            description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
            render: shell
