name: Enhancement
description: Do you have a suggestion for a new feature or a way to improve Refined Storage? Let us know.
labels: [ enhancement ]
body:
    -   type: textarea
        id: describe-it
        attributes:
            label: Describe your enhancement
        validations:
            required: true
